BINARY := apfel-tag
VERSION_FILE := .version
PREFIX ?= /usr/local

.PHONY: check-toolchain build install uninstall test unit preflight release \
        bump-patch bump-minor bump-major version generate-man-page \
        generate-build-info package-release-asset print-release-sha256 \
        update-readme update-homebrew-formula

check-toolchain:
	@sdk=$$(xcrun --show-sdk-version 2>/dev/null || echo "0.0"); \
	major=$$(echo "$$sdk" | cut -d. -f1); \
	if [ "$$major" -lt 26 ]; then \
		echo "error: apfel-tag requires the macOS 26 SDK or newer (found $$sdk)."; exit 1; \
	fi

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown"); \
	date=$$(git log -1 --format='%cd' --date=format:'%Y-%m-%d' 2>/dev/null || date -u +"%Y-%m-%d"); \
	tmp=$$(mktemp); \
	echo "// Auto-generated by make — do not edit" > "$$tmp"; \
	echo "let buildVersion = \"$$v\"" >> "$$tmp"; \
	echo "let buildCommit = \"$$commit\"" >> "$$tmp"; \
	echo "let buildDate = \"$$date\"" >> "$$tmp"; \
	if ! cmp -s "$$tmp" Sources/BuildInfo.swift 2>/dev/null; then mv "$$tmp" Sources/BuildInfo.swift; else rm "$$tmp"; fi

generate-man-page:
	@v=$$(cat $(VERSION_FILE)); \
	[ -f man/$(BINARY).1.in ] || { echo "error: missing man/$(BINARY).1.in"; exit 1; }; \
	mkdir -p .build/release; \
	sed "s/@VERSION@/$$v/g" man/$(BINARY).1.in > .build/release/$(BINARY).1; \
	if command -v mandoc >/dev/null 2>&1; then \
		mandoc -Tlint -W warning .build/release/$(BINARY).1 >/dev/null 2>&1 || { \
			echo "error: mandoc -Tlint failed"; mandoc -Tlint -W warning .build/release/$(BINARY).1; exit 1; }; \
	fi

build: check-toolchain generate-build-info
	swift build -c release
	@$(MAKE) --no-print-directory generate-man-page

unit:
	swift run apfel-tag-tests

install: build
	@install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY)
	@man_dir="$(PREFIX)/share/man/man1"; mkdir -p "$$man_dir"; \
	install -m 0644 .build/release/$(BINARY).1 "$$man_dir/$(BINARY).1"
	@echo "✓ installed: $(BINARY) v$$(cat $(VERSION_FILE))"

uninstall:
	@rm -f $(PREFIX)/bin/$(BINARY) $(PREFIX)/share/man/man1/$(BINARY).1; echo "✓ uninstalled"

test: build unit
	@echo "\n=== Integration tests ==="
	@python3 -m pytest Tests/integration/ -v --tb=short

bump-patch:
	@v=$$(cat $(VERSION_FILE)); a=$$(echo $$v|cut -d. -f1); b=$$(echo $$v|cut -d. -f2); c=$$(echo $$v|cut -d. -f3); \
	n="$$a.$$b.$$((c+1))"; echo "$$n" > $(VERSION_FILE); echo "$$v → $$n"
bump-minor:
	@v=$$(cat $(VERSION_FILE)); a=$$(echo $$v|cut -d. -f1); b=$$(echo $$v|cut -d. -f2); \
	n="$$a.$$((b+1)).0"; echo "$$n" > $(VERSION_FILE); echo "$$v → $$n"
bump-major:
	@v=$$(cat $(VERSION_FILE)); a=$$(echo $$v|cut -d. -f1); \
	n="$$((a+1)).0.0"; echo "$$n" > $(VERSION_FILE); echo "$$v → $$n"

version:
	@cat $(VERSION_FILE)

update-readme:
	@v=$$(cat $(VERSION_FILE)); \
	sed -i '' 's/version-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-blue/version-'"$$v"'-blue/' README.md 2>/dev/null || true

package-release-asset:
	@v=$$(cat $(VERSION_FILE)); asset="$(BINARY)-$$v-arm64-macos.tar.gz"; \
	tar -C .build/release -czf "$$asset" $(BINARY) $(BINARY).1; echo "$$asset"

print-release-sha256:
	@v=$$(cat $(VERSION_FILE)); shasum -a 256 "$(BINARY)-$$v-arm64-macos.tar.gz" | awk '{print $$1}'

update-homebrew-formula:
	@scripts/write-homebrew-formula.sh --version "$$(cat $(VERSION_FILE))" \
		--sha256 "$(HOMEBREW_FORMULA_SHA256)" --output "$(HOMEBREW_FORMULA_OUTPUT)"

preflight:
	@scripts/release-preflight.sh

TYPE ?= patch
release:
	@scripts/publish-release.sh $(TYPE)

release-patch: check-toolchain bump-patch generate-build-info update-readme build
release-minor: check-toolchain bump-minor generate-build-info update-readme build
release-major: check-toolchain bump-major generate-build-info update-readme build
